kube-prometheus-stack:
  grafana:
    adminPassword: "admin"  # Change this for production!
    service:
      type: NodePort

  prometheus:
    prometheusSpec:
      retention: 5d  # Keep metrics for 5 days to save local disk space
